"""Generate src/captcha/charset.rs from charset_old.txt.

charset_old.txt was extracted from ddddocr's charsets.py (CHARSET_OLD).
Output is a Rust source file with a `CHARSET: &[char]` constant indexed by
model output class id (0 = CTC blank, 1..=8209 = real characters).
"""
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INPUT = ROOT / "charset_old.txt"
OUTPUT = ROOT / "src" / "captcha" / "charset.rs"


def rust_char(cp: int) -> str:
    """Format a Unicode codepoint as a Rust char literal."""
    if cp == 0:
        return r"'\u{0}'"
    if cp < 0x20 or cp in (0x27, 0x5c):  # control, single quote, backslash
        return rf"'\u{{{cp:x}}}'"
    if cp < 0x80:
        return f"'{chr(cp)}'"
    return rf"'\u{{{cp:x}}}'"


def main() -> int:
    if not INPUT.exists():
        print(f"missing input: {INPUT}", file=sys.stderr)
        return 1

    entries = []
    with INPUT.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue
            idx_str, char_repr = line.split("\t", 1)
            idx = int(idx_str)
            ch = ast.literal_eval(char_repr)
            cp = ord(ch) if ch else 0
            entries.append((idx, rust_char(cp)))

    lines = [
        "// AUTO-GENERATED by tools/gen_charset.py — do not edit.",
        "//",
        "// Character set extracted from ddddocr v1.x charsets.py (CHARSET_OLD,",
        f"// {len(entries)} entries: index 0 is the CTC blank, 1..={len(entries)-1} are recognition classes).",
        "",
        "#[rustfmt::skip]",
        f"pub const CHARSET: &[char] = &[",
    ]
    for idx, r in entries:
        lines.append(f"    {r}, // {idx}")
    lines.append("];")
    lines.append("")
    lines.append(f"pub const CHARSET_LEN: usize = CHARSET.len();")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())